// Liero26 - Weapon Definitions
// All 40 weapons from original Liero v1.33

;(function() {
var WEAPONS = [
  {
    id: 0, name: 'SHOTGUN', speed: 250, gravity: 700/65536, parts: 15, ammo: 5,
    loadingTime: 235, delay: 57, recoil: 55, hitDamage: 1, bloodOnHit: 3,
    distribution: 12000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 4, fireCone: 9, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'shotgun',
    createOnExp: 'small',
  },
  {
    id: 1, name: 'CHAINGUN', speed: 250, gravity: 700/65536, parts: 5, ammo: 100,
    loadingTime: 15, delay: 5, recoil: 10, hitDamage: 1, bloodOnHit: 3,
    distribution: 5000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 2, fireCone: 5, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'shot',
    createOnExp: 'small',
  },
  {
    id: 2, name: 'RIFLE', speed: 500, gravity: 0, parts: 1, ammo: 4,
    loadingTime: 350, delay: 0, recoil: 80, hitDamage: 18, bloodOnHit: 50,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'rifle',
    createOnExp: 'small',
  },
  {
    id: 3, name: 'BAZOOKA', speed: 200, gravity: 0, parts: 1, ammo: 3,
    loadingTime: 410, delay: 75, recoil: 15, hitDamage: 12, bloodOnHit: 30,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 9, shotType: 3, color: 0, splinterAmount: 12,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'bazooka',
    startFrame: 2, createOnExp: 'large',
  },
  {
    id: 4, name: 'DIRTBALL', speed: 120, gravity: 1300/65536, parts: 1, ammo: 10,
    loadingTime: 120, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 5000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 2, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 1, wormCollide: false, groundCollide: false,
    affectByExplosions: false, laserSight: false, sound: 'throw',
    dirtEffect: true, createOnExp: 'dirt',
  },
  {
    id: 5, name: 'EXPLOSIVES', speed: 100, gravity: 1300/65536, parts: 1, ammo: 1,
    loadingTime: 420, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 0, bounce: 40, timeToExplo: 300, timeToExploV: 50,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 50,
    leaveShells: false, exploSize: 2, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    startFrame: 4, createOnExp: 'large',
  },
  {
    id: 6, name: 'MINE', speed: 100, gravity: 1300/65536, parts: 1, ammo: 3,
    loadingTime: 290, delay: 0, recoil: 0, hitDamage: 8, bloodOnHit: 20,
    distribution: 0, bounce: 20, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 30,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    detectDistance: 15, startFrame: 6, createOnExp: 'large',
  },
  {
    id: 7, name: 'WINCHESTER', speed: 300, gravity: 0, parts: 1, ammo: 5,
    loadingTime: 260, delay: 0, recoil: 60, hitDamage: 14, bloodOnHit: 40,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 5, fireCone: 0, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'rifle',
    createOnExp: 'small',
  },
  {
    id: 8, name: 'DOOMSDAY', speed: 150, gravity: 0, parts: 1, ammo: 1,
    loadingTime: 600, delay: 0, recoil: 20, hitDamage: 0, bloodOnHit: 0,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 80,
    leaveShells: false, exploSize: 3, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'bazooka',
    startFrame: 2, createOnExp: 'large',
  },
  {
    id: 9, name: 'FLAMER', speed: 110, gravity: -200/65536, parts: 1, ammo: 200,
    loadingTime: 5, delay: 0, recoil: 0, hitDamage: 1, bloodOnHit: 0,
    distribution: 8000/65536, bounce: 0, timeToExplo: 30, timeToExploV: 10,
    blowAway: 0, fireCone: 5, shotType: 1, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: true, groundCollide: false,
    affectByExplosions: false, laserSight: false, sound: 'burner',
    colorAnim: { from: 129, to: 131 }, createOnExp: 'tiny',
  },
  {
    id: 10, name: 'GRENADE', speed: 170, gravity: 1300/65536, parts: 1, ammo: 1,
    loadingTime: 260, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 7000/65536, bounce: 40, timeToExplo: 115, timeToExploV: 10,
    blowAway: 0, fireCone: 0, shotType: 0, color: 0, splinterAmount: 50,
    leaveShells: false, exploSize: 2, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    startFrame: 96, numFrames: 3, loopAnim: true, createOnExp: 'large',
  },
  {
    id: 11, name: 'LARPA', speed: 150, gravity: 0, parts: 1, ammo: 3,
    loadingTime: 310, delay: 0, recoil: 15, hitDamage: 5, bloodOnHit: 15,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 8,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'larpa',
    startFrame: 2, createOnExp: 'medium',
  },
  {
    id: 12, name: 'BLASTER', speed: 80, gravity: 0, parts: 1, ammo: 50,
    loadingTime: 50, delay: 0, recoil: 15, hitDamage: 0, bloodOnHit: 0,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 25, fireCone: 0, shotType: 3, color: 0, splinterAmount: 5,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'blaster',
    startFrame: 2, createOnExp: 'medium',
  },
  {
    id: 13, name: 'BOUNCY MINE', speed: 130, gravity: 1000/65536, parts: 1, ammo: 3,
    loadingTime: 290, delay: 0, recoil: 0, hitDamage: 10, bloodOnHit: 25,
    distribution: 0, bounce: 70, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 30,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    detectDistance: 15, startFrame: 6, createOnExp: 'large',
  },
  {
    id: 14, name: 'MINIGUN', speed: 350, gravity: 0, parts: 3, ammo: 50,
    loadingTime: 25, delay: 3, recoil: 8, hitDamage: 2, bloodOnHit: 5,
    distribution: 6000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 1, fireCone: 7, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'shot',
    createOnExp: 'small',
  },
  {
    id: 15, name: 'CLUSTER BOMB', speed: 160, gravity: 1300/65536, parts: 1, ammo: 2,
    loadingTime: 350, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 5000/65536, bounce: 30, timeToExplo: 100, timeToExploV: 10,
    blowAway: 0, fireCone: 0, shotType: 0, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 1, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    spawnOnExplo: 'cluster', startFrame: 96, numFrames: 3, loopAnim: true,
    createOnExp: 'medium',
  },
  {
    id: 16, name: 'SUPER SHOTGUN', speed: 200, gravity: 600/65536, parts: 30, ammo: 3,
    loadingTime: 350, delay: 100, recoil: 80, hitDamage: 1, bloodOnHit: 3,
    distribution: 18000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 3, fireCone: 15, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'shotgun',
    createOnExp: 'small',
  },
  {
    id: 17, name: 'HANDGUN', speed: 300, gravity: 0, parts: 1, ammo: 12,
    loadingTime: 90, delay: 0, recoil: 15, hitDamage: 5, bloodOnHit: 15,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 2, fireCone: 3, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'shot',
    createOnExp: 'small',
  },
  {
    id: 18, name: 'GREENBALL', speed: 100, gravity: 0, parts: 1, ammo: 50,
    loadingTime: 30, delay: 0, recoil: 3, hitDamage: 2, bloodOnHit: 5,
    distribution: 3000/65536, bounce: 0, timeToExplo: 60, timeToExploV: 10,
    blowAway: 0, fireCone: 3, shotType: 1, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: true, groundCollide: false,
    affectByExplosions: false, laserSight: false, sound: 'blaster',
    colorAnim: { from: 133, to: 136 }, createOnExp: 'tiny',
  },
  {
    id: 19, name: 'BIG NUKE', speed: 130, gravity: 1300/65536, parts: 1, ammo: 1,
    loadingTime: 600, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 5000/65536, bounce: 25, timeToExplo: 200, timeToExploV: 30,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 100,
    leaveShells: false, exploSize: 4, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    startFrame: 2, createOnExp: 'huge',
  },
  {
    id: 20, name: 'CRACKLER', speed: 120, gravity: 0, parts: 1, ammo: 3,
    loadingTime: 350, delay: 0, recoil: 10, hitDamage: 3, bloodOnHit: 10,
    distribution: 0, bounce: 60, timeToExplo: 150, timeToExploV: 20,
    blowAway: 0, fireCone: 0, shotType: 1, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: false,
    affectByExplosions: false, laserSight: false, sound: 'larpa',
    colorAnim: { from: 152, to: 159 }, spawnOnExplo: 'crackler',
    createOnExp: 'medium',
  },
  {
    id: 21, name: 'ZIMM', speed: 400, gravity: 0, parts: 1, ammo: 1,
    loadingTime: 500, delay: 0, recoil: 100, hitDamage: 30, bloodOnHit: 80,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 0, color: 104, splinterAmount: 0,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: true, sound: 'rifle',
    createOnExp: 'medium',
  },
  {
    id: 22, name: 'MINI NUKE', speed: 140, gravity: 1000/65536, parts: 1, ammo: 2,
    loadingTime: 420, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 3000/65536, bounce: 30, timeToExplo: 120, timeToExploV: 15,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 40,
    leaveShells: false, exploSize: 2, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    startFrame: 2, createOnExp: 'large',
  },
  {
    id: 23, name: 'FLOAT MINE', speed: 80, gravity: -100/65536, parts: 1, ammo: 5,
    loadingTime: 200, delay: 0, recoil: 0, hitDamage: 8, bloodOnHit: 20,
    distribution: 0, bounce: 30, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 25,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    detectDistance: 20, startFrame: 6, createOnExp: 'large',
  },
  {
    id: 24, name: 'FAN', speed: 250, gravity: 0, parts: 1, ammo: 100,
    loadingTime: 10, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 2000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 30, fireCone: 5, shotType: 0, color: 168, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: null,
    createOnExp: 'tiny',
  },
  {
    id: 25, name: 'HELLRAIDER', speed: 130, gravity: 0, parts: 1, ammo: 1,
    loadingTime: 500, delay: 0, recoil: 15, hitDamage: 0, bloodOnHit: 0,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: false, groundCollide: false,
    affectByExplosions: false, laserSight: false, sound: 'bazooka',
    spawnsProjectiles: true, startFrame: 2, createOnExp: 'medium',
  },
  {
    id: 26, name: 'CANNON', speed: 200, gravity: 500/65536, parts: 1, ammo: 3,
    loadingTime: 350, delay: 75, recoil: 40, hitDamage: 10, bloodOnHit: 25,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 15, fireCone: 5, shotType: 3, color: 0, splinterAmount: 10,
    leaveShells: true, exploSize: 1, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'bazooka',
    startFrame: 2, createOnExp: 'medium',
  },
  {
    id: 27, name: 'BOUNCY LARPA', speed: 130, gravity: 0, parts: 1, ammo: 3,
    loadingTime: 350, delay: 0, recoil: 10, hitDamage: 3, bloodOnHit: 10,
    distribution: 0, bounce: 80, timeToExplo: 200, timeToExploV: 30,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 10,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'larpa',
    startFrame: 2, createOnExp: 'medium',
  },
  {
    id: 28, name: 'LASER', speed: 100, gravity: 0, parts: 1, ammo: 80,
    loadingTime: 400, delay: 0, recoil: 0, hitDamage: 1, bloodOnHit: 0,
    distribution: 10/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 4, color: 104, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: true, laserSight: false, sound: null,
    isLaser: true, createOnExp: 'tiny',
  },
  {
    id: 29, name: 'SPIKEBALLS', speed: 80, gravity: 1300/65536, parts: 3, ammo: 3,
    loadingTime: 280, delay: 30, recoil: 0, hitDamage: 5, bloodOnHit: 15,
    distribution: 10000/65536, bounce: 50, timeToExplo: 200, timeToExploV: 30,
    blowAway: 0, fireCone: 10, shotType: 3, color: 0, splinterAmount: 5,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    startFrame: 6, createOnExp: 'small',
  },
  {
    id: 30, name: 'NAPALM', speed: 160, gravity: 1300/65536, parts: 1, ammo: 2,
    loadingTime: 400, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 5000/65536, bounce: 20, timeToExplo: 80, timeToExploV: 10,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 1, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    spawnOnExplo: 'napalm', startFrame: 2, createOnExp: 'medium',
  },
  {
    id: 31, name: 'UZI', speed: 300, gravity: 0, parts: 1, ammo: 60,
    loadingTime: 15, delay: 5, recoil: 5, hitDamage: 3, bloodOnHit: 8,
    distribution: 3000/65536, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 1, fireCone: 5, shotType: 0, color: 75, splinterAmount: 0,
    leaveShells: true, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'shot',
    createOnExp: 'small',
  },
  {
    id: 32, name: 'MISSILE', speed: 70, gravity: 0, parts: 1, ammo: 3,
    loadingTime: 380, delay: 0, recoil: 10, hitDamage: 10, bloodOnHit: 25,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 20,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'bazooka',
    accelerating: true, startFrame: 2, createOnExp: 'large',
  },
  {
    id: 33, name: 'CHIQUITA BOMB', speed: 150, gravity: 1300/65536, parts: 1, ammo: 1,
    loadingTime: 450, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 5000/65536, bounce: 30, timeToExplo: 120, timeToExploV: 15,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 2, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    spawnOnExplo: 'chiquita', startFrame: 2, createOnExp: 'large',
  },
  {
    id: 34, name: 'BOOBY TRAP', speed: 0, gravity: 1300/65536, parts: 1, ammo: 3,
    loadingTime: 200, delay: 0, recoil: 0, hitDamage: 8, bloodOnHit: 20,
    distribution: 0, bounce: 20, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 0, shotType: 3, color: 0, splinterAmount: 25,
    leaveShells: false, exploSize: 2, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: null,
    detectDistance: 12, startFrame: 6, invisible: true, createOnExp: 'large',
  },
  {
    id: 35, name: 'GRASSHOPPER', speed: 100, gravity: 1300/65536, parts: 1, ammo: 2,
    loadingTime: 380, delay: 0, recoil: 0, hitDamage: 0, bloodOnHit: 0,
    distribution: 5000/65536, bounce: 60, timeToExplo: 400, timeToExploV: 50,
    blowAway: 0, fireCone: 0, shotType: 0, color: 0, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: false, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'throw',
    grasshopper: true, startFrame: 96, numFrames: 3, loopAnim: true,
    createOnExp: 'medium',
  },
  {
    id: 36, name: 'MINI ROCKETS', speed: 150, gravity: 0, parts: 1, ammo: 8,
    loadingTime: 100, delay: 25, recoil: 20, hitDamage: 5, bloodOnHit: 15,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 5, fireCone: 5, shotType: 3, color: 0, splinterAmount: 5,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'bazooka',
    startFrame: 2, createOnExp: 'small',
  },
  {
    id: 37, name: 'DART', speed: 280, gravity: 0, parts: 1, ammo: 10,
    loadingTime: 150, delay: 0, recoil: 10, hitDamage: 8, bloodOnHit: 20,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 0, fireCone: 3, shotType: 0, color: 72, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: false, sound: 'throw',
    createOnExp: 'tiny',
  },
  {
    id: 38, name: 'RB RAMPAGE', speed: 200, gravity: 0, parts: 5, ammo: 2,
    loadingTime: 400, delay: 50, recoil: 30, hitDamage: 3, bloodOnHit: 10,
    distribution: 5000/65536, bounce: 70, timeToExplo: 200, timeToExploV: 30,
    blowAway: 0, fireCone: 10, shotType: 3, color: 0, splinterAmount: 5,
    leaveShells: false, exploSize: 1, wormCollide: true, groundCollide: false,
    affectByExplosions: true, laserSight: false, sound: 'larpa',
    startFrame: 2, createOnExp: 'small',
  },
  {
    id: 39, name: 'GAUSS GUN', speed: 500, gravity: 0, parts: 1, ammo: 3,
    loadingTime: 450, delay: 0, recoil: 100, hitDamage: 25, bloodOnHit: 60,
    distribution: 0, bounce: 0, timeToExplo: 0, timeToExploV: 0,
    blowAway: 10, fireCone: 0, shotType: 4, color: 104, splinterAmount: 0,
    leaveShells: false, exploSize: 0, wormCollide: true, groundCollide: true,
    affectByExplosions: false, laserSight: true, sound: 'rifle',
    isLaser: true, createOnExp: 'small',
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = WEAPONS;
} else if (typeof window !== 'undefined') {
  window.WEAPONS = WEAPONS;
}

})();
